services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: ${COMPOSE_PROJECT_NAME:-autohall}-mssql
    ports:
      - "${DB_PORT_HOST:-1433}:1433"
    environment:
      - ACCEPT_EULA=${ACCEPT_EULA}
      - SA_PASSWORD=${SA_PASSWORD}
    volumes:
      - mssql_data:/var/opt/mssql
    restart: unless-stopped

volumes:
  mssql_data:
